language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

install:
  - go get -d -t -v ./...
  - go install -v

script:
  - go vet ./...
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
